//------------------------------------------------------------------------
// Copyright(c) 2025 ASKA.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"filtros2.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"filtros2 VST3 (64Bit)"
#else
#define stringFileDescription	"filtros2 VST3"
#endif
#define stringCompanyName		"ASKA\0"
#define stringLegalCopyright	"Copyright(c) 2025 ASKA."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
